const questionType = {
  GET_QUESTION_TOPICS: "GET_QUESTION_TOPICS",
  GET_ALL_QUESTIONS: "GET_ALL_QUESTIONS",
  UPDATE_QUESTION_STATUS: "UPDATE_QUESTION_STATUS",
  GET_ASKED_QUESTIONS: "GET_ASKED_QUESTIONS",
  GET_ACTIVE_QUESTION: "GET_ACTIVE_QUESTION",
  GET_QUESTIONS_DETAIL: "GET_QUESTIONS_DETAIL",
  GET_TOPIC_QUESTIONS: "GET_TOPIC_QUESTIONS",
  GET_QUESTION_DETAIL: "GET_QUESTION_DETAIL",
  REMOVE_QUESTION: "REMOVE_QUESTION",
  RESET_TIMER_STATUS: "RESET_TIMER_STATUS",
};

export default questionType;
