export const questionType = {
  GET_QUESTION_TOPICS: "GET_QUESTION_TOPICS",
  GET_ALL_QUESTIONS: "GET_ALL_QUESTIONS",
  GET_ACTIVE_QUESTION: "GET_ACTIVE_QUESTION",
  GET_QUESTIONS_DETAIL: "GET_QUESTIONS_DETAIL",
  GET_QUESTION_DETAIL: "GET_QUESTION_DETAIL",
  REMOVE_QUESTION: "REMOVE_QUESTION",
};
