const studentType = {
  GET_STUDENTS_DETAIL: "GET_STUDENTS_DETAIL",
  GET_LATEST_STUDENTS: "GET_LATEST_STUDENTS",
  GET_STUDENT_DETAIL: "GET_STUDENT_DETAIL",
  REMOVE_STUDENT: "REMOVE_STUDENT",
  UPDATE_STATUS: "UPDATE_STATUS",
  GET_PARTICIPANTS: "GET_PARTICIPANTS",
};

export default studentType;
